{{- if .Values.networkPolicy.enabled }}
# Default deny all ingress and egress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "audiobookshelf.fullname" . }}-default-deny
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
# Allow ingress from ingress controller namespace on port 80
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "audiobookshelf.fullname" . }}-allow-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "audiobookshelf.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}
---
# Allow egress to kube-dns for DNS resolution
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "audiobookshelf.fullname" . }}-allow-dns
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "audiobookshelf.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- if .Values.networkPolicy.allowMetadataFetching }}
---
# Allow egress to internet for metadata/cover art fetching
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "audiobookshelf.fullname" . }}-allow-internet
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "audiobookshelf.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
{{- end }}
{{- end }}
