apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "audiobookshelf.fullname" . }}-metadata
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
    app.kubernetes.io/component: metadata
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: {{ .Values.persistence.metadata.hostPath }}
    type: DirectoryOrCreate
  claimRef:
    namespace: {{ .Values.namespace }}
    name: {{ include "audiobookshelf.fullname" . }}-metadata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "audiobookshelf.fullname" . }}-metadata
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
    app.kubernetes.io/component: metadata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: {{ include "audiobookshelf.fullname" . }}-metadata
